### ISSUE TITLE
Issues on 2019.8.9

### ISSUE THREAD

**Issue by davidsandilands** [puppetlabs/puppetlabs-puppet_data_service#1]
## Describe the Bug
PDS-migrations fails to run and errors exit 2 on 2019.8.9

```
Notice: /Stage[main]/Puppet_data_service::Server/File[/etc/puppetlabs/pds/pds-server.yaml]/content: content changed '{md5}3f86759b0cb5871c4a018831388010ba' to '{md5}4a0422f4ea78b238b80ac6858cb42d76'
Info: /Stage[main]/Puppet_data_service::Server/File[/etc/puppetlabs/pds/pds-server.yaml]: Scheduling refresh of Service[pds-server]
Notice: /Stage[main]/Puppet_data_service::Server/Exec[pds-migrations]/returns: [output redacted]
Error: [command redacted] returned 2 instead of one of [0]
Error: /Stage[main]/Puppet_data_service::Server/Exec[pds-migrations]/returns: change from 'notrun' to ['0'] failed: [command redacted] returned 2 instead of one of [0] (corrective)
Notice: /Stage[main]/Puppet_data_service::Server/Service[pds-server]: Dependency Exec[pds-migrations] has failures: true
Warning: /Stage[main]/Puppet_data_service::Server/Service[pds-server]: Skipping because of failed dependencies
```

## Expected Behavior
pds-migrations should run correctly

## Steps to Reproduce
Run the install on a 2019.8.9 server

## Environment
PE 2019.8.9

## Additional Context
Disccused with Edwin who verified this is an issue he experienced

**Comment by reidmv** [comment]
We haven't yet built RPMs for PE 2019.x.

I've updated the RPMs we've built so far to have a version dependency on pe-postgresql11, so they shouldn't install on PE 2019. Will raise a dependency error.

I've also updated the RPM name to include the PE build number it was compiled with. That should help users figure out what might be going on, and what might be compatible.

**Comment by davidsandilands** [comment]
@timidri ticket SOLARCH-761 resolves this issue
